<a href="https://colab.research.google.com/github/paulinagorska1987/machine_learning_bootcamp/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import bibliotek

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

In [ ]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'male'],
    'price': [199.0, 89.0, 99, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}


df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red    male   79.0     410    yes

In [ ]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [ ]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [ ]:
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [ ]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [ ]:
df.describe(include=['category']).T

count unique    top freq
size       5      3      L    2
color      5      3  green    2
gender     5      2   male    3
bought     5      2    yes    3

2. LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder # klasa używana do przekształcania zmiennej wynikowej

le = LabelEncoder() # tworzymy instancję klasy
le.fit(df['bought']) # dopasowuje encoder do naszej zmiennej
le.transform(df['bought']) # metoda transformuje dane; zwrócone 0 i 1;


array([1, 0, 1, 0, 1])

In [ ]:
le.fit_transform(df['bought']) # metod fit i transform nie trzeba stosować oddzielnie

array([1, 0, 1, 0, 1])

In [ ]:
le.classes_ # wyświetla mapowanie (która kategoria jakiej liczbie odpowiada)

array(['no', 'yes'], dtype=object)

In [ ]:
df['bought'] = le.fit_transform(df['bought']) # zamieniamy to, co jest w df

In [ ]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red    male   79.0   410.0       1

In [ ]:
le.inverse_transform(df['bought']) # można wrócić do stanu sprzed transformacji

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [ ]:
df['bought']=le.inverse_transform(df['bought'])

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red    male   79.0   410.0    yes

In [ ]:
df['bought'] = le.fit_transform(df['bought'])

In [ ]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red    male   79.0   410.0       1

3. OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder # importujemy klasę; utworzy k zmiennych gdzie k to liczba kategorii zmiennej

In [ ]:
encoder = OneHotEncoder(sparse = False) # tworzymy instancję, ale nie macierz rzadką

In [ ]:
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [ ]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
encoder.categories_ # mówi, co jest w kolumnach

[array(['L', 'M', 'XL'], dtype=object)]

In [ ]:
encoder = OneHotEncoder(drop='first', sparse=False) # nowa instancja, robi dummies dla wybranej zmiennej z pierwszą kategorią jako kategorią odniesienia

In [ ]:
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(drop='first', sparse=False, sparse_output=False)

In [ ]:
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

4. Pandas *get_dummies()*

In [ ]:
pd.get_dummies(data=df)

price  weight  bought  size_L  size_M  size_XL  color_blue  color_green  \
0  199.0   500.0       1       0       0        1           0            0   
1   89.0   450.0       0       1       0        0           0            1   
2   99.0   300.0       1       0       1        0           1            0   
3  129.0   380.0       0       1       0        0           0            1   
4   79.0   410.0       1       0       1        0           0            0   

   color_red  gender_female  gender_male  
0          1              1            0  
1          0              0            1  
2          0              0            1  
3          0              1            0  
4          1              0            1

In [ ]:
pd.get_dummies(data=df, drop_first=True) # zmienna dla pierwszej kategorii jest usuwana, jest kategorią odniesienia

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2   99.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            1

In [ ]:
pd.get_dummies(data=df, drop_first=True, prefix = 'new') # każda nowa kolumna będzie zaczynała się od prefixi

price  weight  bought  new_M  new_XL  new_green  new_red  new_male
0  199.0   500.0       1      0       1          0        1         0
1   89.0   450.0       0      0       0          1        0         1
2   99.0   300.0       1      1       0          0        0         1
3  129.0   380.0       0      0       0          1        0         0
4   79.0   410.0       1      1       0          0        1         1

In [ ]:
pd.get_dummies(data=df, drop_first=True, prefix_sep="-") # można zmienić separator (domyślnie - podkreślnik)

price  weight  bought  size-M  size-XL  color-green  color-red  gender-male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2   99.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            1

5. Standaryzacja Danych

std() - pandas nieobciążony

std() - numy obciążony

In [ ]:
print(f"{df['price']}/n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64/n
Średnia: 119.0
Odchylenie standardowe: 48.4768


In [ ]:
(df['price']-df['price'].mean())/df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [ ]:
def standardize(x):
  return (x-x.mean())/x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [ ]:
from sklearn.preprocessing import scale

In [ ]:
scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler_price = StandardScaler()

In [ ]:
df['price'] = scaler_price.fit_transform(df[['price']])

In [ ]:
df[['price', 'weight']] = scaler_price.fit_transform(df[['price', 'weight']]) # standaryzujemy kilka cech za jednym zamachem

In [ ]:
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red    male -0.922531  0.029696       1

Przygotowanie od poczatku


In [ ]:
df = df_raw.copy()

In [ ]:
le = LabelEncoder()

In [ ]:
df['bought'] = le.fit_transform(df['bought'])

In [ ]:
scaler = StandardScaler()

In [ ]:
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

In [ ]:
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red    male -0.922531  0.029696       1

In [ ]:
df=pd.get_dummies(data=df, drop_first=True)

In [ ]:
df