<a href="https://colab.research.google.com/github/paulinagorska1987/machine_learning_bootcamp/blob/main/01_basics/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import bibliotek

In [1]:
import numpy as np

In [2]:
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

In [3]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'male'],
    'price': [199.0, 89.0, 990, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}


df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male  990.0     300    yes
3    L  green  female  129.0     380     no
4    M    red    male   79.0     410    yes

from matplotlib import pyplot as plt
df_raw['price'].plot(kind='hist', bins=20, title='price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_raw['weight'].plot(kind='hist', bins=20, title='weight')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df_raw.groupby('size').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df_raw.groupby('color').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df_raw.groupby('gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df_raw.groupby('bought').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_raw.plot(kind='scatter', x='price', y='weight', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_raw['price'].plot(kind='line', figsize=(8, 4), title='price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df_raw['weight'].plot(kind='line', figsize=(8, 4), title='weight')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['color'].value_counts()
    for x_label, grp in df_raw.groupby('size')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('size')
_ = plt.ylabel('color')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['gender'].value_counts()
    for x_label, grp in df_raw.groupby('color')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('color')
_ = plt.ylabel('gender')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['bought'].value_counts()
    for x_label, grp in df_raw.groupby('gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('gender')
_ = plt.ylabel('bought')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df_raw['size'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df_raw, x='price', y='size', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df_raw['color'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df_raw, x='price', y='color', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df_raw['gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df_raw, x='price', y='gender', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df_raw['bought'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df_raw, x='price', y='bought', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [6]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [7]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [9]:
df.describe()

price      weight
count    5.000000    5.000000
mean   297.200000  408.000000
std    390.148946   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%    129.000000  410.000000
75%    199.000000  450.000000
max    990.000000  500.000000

In [10]:
df.describe().T

count   mean         std    min    25%    50%    75%    max
price     5.0  297.2  390.148946   79.0   89.0  129.0  199.0  990.0
weight    5.0  408.0   75.299402  300.0  380.0  410.0  450.0  500.0

In [11]:
df.describe(include=['category']).T

count unique    top freq
size       5      3      L    2
color      5      3  green    2
gender     5      2   male    3
bought     5      2    yes    3

2. LabelEncoder

In [15]:
from sklearn.preprocessing import LabelEncoder # klasa używana do przekształcania zmiennej wynikowej

le = LabelEncoder() # tworzymy instancję klasy
le.fit(df['bought']) # dopasowuje encoder do naszej zmiennej
le.transform(df['bought']) # metoda transformuje dane; zwrócone 0 i 1;


array([1, 0, 1, 0, 1])

In [16]:
le.fit_transform(df['bought']) # metod fit i transform nie trzeba stosować oddzielnie

array([1, 0, 1, 0, 1])

In [17]:
le.classes_ # wyświetla mapowanie (która kategoria jakiej liczbie odpowiada)

array(['no', 'yes'], dtype=object)

In [18]:
df['bought'] = le.fit_transform(df['bought']) # zamieniamy to, co jest w df

In [19]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male  990.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red    male   79.0   410.0       1

In [21]:
le.inverse_transform(df['bought']) # można wrócić do stanu sprzed transformacji

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [22]:
df['bought']=le.inverse_transform(df['bought'])

In [23]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male  990.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red    male   79.0   410.0    yes

In [24]:
df['bought'] = le.fit_transform(df['bought'])

In [25]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male  990.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red    male   79.0   410.0       1

3. OneHotEncoder

In [26]:
from sklearn.preprocessing import OneHotEncoder # importujemy klasę; utworzy k zmiennych gdzie k to liczba kategorii zmiennej

In [28]:
encoder = OneHotEncoder(sparse = False) # tworzymy instancję, ale nie macierz rzadką

In [29]:
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [30]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [32]:
encoder.categories_ # mówi, co jest w kolumnach

[array(['L', 'M', 'XL'], dtype=object)]

In [37]:
encoder = OneHotEncoder(drop='first', sparse=False) # nowa instancja, robi dummies dla wybranej zmiennej z pierwszą kategorią jako kategorią odniesienia

In [39]:
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(drop='first', sparse=False, sparse_output=False)

In [40]:
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

4. Pandas *get_dummies()*

In [41]:
pd.get_dummies(data=df)

price  weight  bought  size_L  size_M  size_XL  color_blue  color_green  \
0  199.0   500.0       1       0       0        1           0            0   
1   89.0   450.0       0       1       0        0           0            1   
2  990.0   300.0       1       0       1        0           1            0   
3  129.0   380.0       0       1       0        0           0            1   
4   79.0   410.0       1       0       1        0           0            0   

   color_red  gender_female  gender_male  
0          1              1            0  
1          0              0            1  
2          0              0            1  
3          0              1            0  
4          1              0            1

In [42]:
pd.get_dummies(data=df, drop_first=True) # zmienna dla pierwszej kategorii jest usuwana, jest kategorią odniesienia

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2  990.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            1

In [43]:
pd.get_dummies(data=df, drop_first=True, prefix = 'new') # każda nowa kolumna będzie zaczynała się od prefixi

price  weight  bought  new_M  new_XL  new_green  new_red  new_male
0  199.0   500.0       1      0       1          0        1         0
1   89.0   450.0       0      0       0          1        0         1
2  990.0   300.0       1      1       0          0        0         1
3  129.0   380.0       0      0       0          1        0         0
4   79.0   410.0       1      1       0          0        1         1

In [44]:
pd.get_dummies(data=df, drop_first=True, prefix_sep="-") # można zmienić separator (domyślnie - podkreślnik)

price  weight  bought  size-M  size-XL  color-green  color-red  gender-male
0  199.0   500.0       1       0        1            0          1            0
1   89.0   450.0       0       0        0            1          0            1
2  990.0   300.0       1       1        0            0          0            1
3  129.0   380.0       0       0        0            1          0            0
4   79.0   410.0       1       1        0            0          1            1

5. Standaryzacja Danych

std() - pandas nieobciążony

std() - numy obciążony